#file: noinspection SpellCheckingInspection
name: ScytheSMP
version: '${project.version}'
main: me.foxils.scythesmp.ScytheSMP
api-version: '1.21'
author: Foxils
description: Plugin for the ScytheSMP

depend:
  - foxutils-items

commands:
  deletegemdata:
    description: Delete a player's gem data permanently
    usage: /<command> <player>
    permission: op
  getlevel:
    description: Get level of the current custom item in your hand
    usage: /<command>
    permission: op