#file: noinspection SpellCheckingInspection
name: SynthSMP
version: '${project.version}'
main: me.foxils.synthsmp.SynthSMP
api-version: '1.21'
author: Foxils
description: Plugin for the SynthSMP

depend:
  - foxutils-items

commands:
  setcraftable:
    description: enable crafting of said one time craftable UberItem
    usage: /<command>
    permission: op
  getLevel:
    description: get custom item level in hand
    usage: /<command>
    permission: op