#file: noinspection SpellCheckingInspection
name: ScytheSMP
version: '${project.version}'
main: me.foxils.scythesmp.ScytheSMP
api-version: '1.21'
author: Foxils
description: Plugin for the ScytheSMP

depend:
  - foxutils-items

commands:
  deletegemdata:
    description: Delete a player's gem data permanently
    usage: /<command> <player>
    permission: op
  getitemlevel:
    description: Get the level of the current UpgradeableItem in your hand
    usage: /<command>
    permission: op
    aliases: [getlevel, levelget]
  setitemlevel:
    description: Set the level of the current UpgradeableItem in your hand
    usage: /<command> <level>
    permission: op
    aliases: [setlevel, levelset]