#file: noinspection SpellCheckingInspection
name: SytheSMP
version: '${project.version}'
main: me.foxils.sytheSMP.SytheSMP
api-version: '1.21'
author: Foxils
description: Plugin for the ?

depend:
  - foxutils-items

commands:
  setcraftable:
    description: enable crafting of said one time craftable UberItem
    usage: /<command>
    permission: op
  get:
    description: get custom item with the item key
    usage: /<command> <itemkey>
    permission: op
  getLevel:
    description: get custom item level in hand
    usage: /<command>
    permission: op
  getItems:
    description: Lists all currently registered items
    usage: /<command>
    permission: op